# This file tells Render how to build and deploy your services.
services:
  # Service 1: The GCP Emulators (runs as a background worker)
  - name: gcp-emulators
    type: worker 
    runtime: docker # <-- THIS LINE WAS MISSING
    dockerfilePath: ./Dockerfile.emulators
    dockerContext: .
    
  # Service 2: The main Spring Boot application (runs as a web service)
  - name: pulsar-app
    type: web 
    runtime: docker # <-- THIS LINE WAS MISSING
    dockerfilePath: ./pulsar-app/Dockerfile
    dockerContext: ./pulsar-app
    # Plan: We use the free plan for our services.
    plan: free
    envVars:
      - key: PUBSUB_EMULATOR_HOST
        value: gcp-emulators:8085
      - key: FIRESTORE_EMULATOR_HOST
        value: gcp-emulators:8086
      - key: GCP_PROJECT_ID
        value: local-project